stages:
  - Build CLI
  - Build Container
  - Publish

Go Build:
  stage: Build CLI
  image: golang:1.16.0
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - cd ./cli
    - go get ./...
    - go build github.com/deepsourcelabs/cli

Kaniko:
  stage: Build Container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push

Publish GitHub - REST API:
  environment: GitHub
  stage: Publish
  only:
    refs:
      - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"elliotcourant\",\"password\":\"$K8S_SECRET_GITHUB_ACCESS_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - make ci-kaniko-push