stages:
  - Build CLI
  - Build Container
  - Publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Go Build:
  stage: Build CLI
  image: golang:1.16.2
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - (cd ./cli && go get ./... && go build github.com/deepsourcelabs/cli)

Kaniko:
  stage: Build Container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push

Publish GitHub - REST API:
  environment: GitHub
  stage: Publish
  only:
    refs:
      - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - k8s:shared
    - arch:amd64
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"ghcr.io\":{\"username\":\"elliotcourant\",\"password\":\"$K8S_SECRET_GITHUB_ACCESS_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - export UPSTREAM-TAG=$(cd ./cli && git describe)
    - echo "Publishing as $UPSTREAM-TAG"
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --build-arg $CI_COMMIT_SHA \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination ghcr.io/harderthanitneedstobe/deepsource:latest \
        --destination ghcr.io/harderthanitneedstobe/deepsource:$UPSTREAM-TAG
